url: http://wengsht.github.com/
pygments: true

title: wengsht
url: http://wengsht.github.com/
feed: /feed.xml
author:
    name: wengsht
    email: wengsht.sysu@gmail.com
    weibo: http://weibo.com/u/1752550681

